<script setup lang="ts">
import { useStore } from "vuex";
import { computed, ref } from "vue";
import { Country } from "../../types";
const store = useStore();

let jsonCountries: Country[] = [
  { code: 'US', name: 'United States' },
  { code: 'RU', name: 'Russian Federation' },
  { code: 'DE', name: 'Germany' },
  { code: 'CA', name: 'Canada' },
  { code: 'PL', name: 'Poland' },
  { code: 'FR', name: 'France' },
  { code: 'PH', name: 'Philippines' },
  { code: 'BR', name: 'Brazil' },
  { code: 'JP', name: 'Japan' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'AU', name: 'Australia' },
  { code: 'TW', name: 'Taiwan' },
  { code: 'CL', name: 'Chile' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'KR', name: 'South Korea' },
  { code: 'UA', name: 'Ukraine' },
  { code: 'MX', name: 'Mexico' },
  { code: 'AR', name: 'Argentina' },
  { code: 'TH', name: 'Thailand' },
  { code: 'CN', name: 'China' },
  { code: 'SG', name: 'Singapore' },
  { code: 'IT', name: 'Italy' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'ES', name: 'Spain' },
  { code: 'FI', name: 'Finland' },
  { code: 'HK', name: 'Hong Kong' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'SE', name: 'Sweden' },
  { code: 'TR', name: 'Turkey' },
  { code: 'PE', name: 'Peru' },
  { code: 'CZ', name: 'Czech Republic' },
  { code: 'RO', name: 'Romania' },
  { code: 'PT', name: 'Portugal' },
  { code: 'NO', name: 'Norway' },
  { code: 'CO', name: 'Colombia' },
  { code: 'HU', name: 'Hungary' },
  { code: 'AT', name: 'Austria' },
  { code: 'BE', name: 'Belgium' },
  { code: 'KZ', name: 'Kazakhstan' },
  { code: 'BY', name: 'Belarus' },
  { code: 'LT', name: 'Lithuania' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'IL', name: 'Israel' },
  { code: 'DK', name: 'Denmark' },
  { code: 'IN', name: 'India' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'GR', name: 'Greece' },
  { code: 'EE', name: 'Estonia' },
  { code: 'BG', name: 'Bulgaria' },
  { code: 'LV', name: 'Latvia' },
  { code: 'SK', name: 'Slovakia' },
  { code: 'EC', name: 'Ecuador' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'RS', name: 'Serbia' },
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'IE', name: 'Ireland' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'HR', name: 'Croatia' },
  { code: 'UY', name: 'Uruguay' },
  { code: 'CR', name: 'Costa Rica' },
  { code: 'SI', name: 'Slovenia' },
  { code: 'MA', name: 'Morocco' },
  { code: 'EG', name: 'Egypt' },
  { code: 'DO', name: 'Dominican Republic' },
  { code: 'MD', name: 'Moldova' },
  { code: 'PA', name: 'Panama' },
  { code: 'GT', name: 'Guatemala' },
  { code: 'DZ', name: 'Algeria' },
  { code: 'BO', name: 'Bolivia' },
  { code: 'MN', name: 'Mongolia' },
  { code: 'KH', name: 'Cambodia' },
  { code: 'TN', name: 'Tunisia' },
  { code: 'BN', name: 'Brunei' },
  { code: 'PR', name: 'Puerto Rico' },
  { code: 'PY', name: 'Paraguay' },
  { code: 'KW', name: 'Kuwait' },
  { code: 'QA', name: 'Qatar' },
  { code: 'NP', name: 'Nepal' },
  { code: 'SV', name: 'El Salvador' },
  { code: 'GE', name: 'Georgia' },
  { code: 'MM', name: 'Myanmar' },
  { code: 'RE', name: 'Reunion' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'TT', name: 'Trinidad and Tobago' },
  { code: 'MO', name: 'Macau' },
  { code: 'HN', name: 'Honduras' },
  { code: 'MK', name: 'North Macedonia' },
  { code: 'LU', name: 'Luxembourg' },
  { code: 'JO', name: 'Jordan' },
  { code: 'BA', name: 'Bosnia and Herzegovina' },
  { code: 'UZ', name: 'Uzbekistan' },
  { code: 'KG', name: 'Kyrgyzstan' },
  { code: 'CY', name: 'Cyprus' },
  { code: 'BH', name: 'Bahrain' },
  { code: 'GU', name: 'Guam' },
  { code: 'LB', name: 'Lebanon' },
  { code: 'IS', name: 'Iceland' },
  { code: 'NI', name: 'Nicaragua' },
  { code: 'MV', name: 'Maldives' },
  { code: 'IQ', name: 'Iraq' },
  { code: 'JM', name: 'Jamaica' },
  { code: 'AZ', name: 'Azerbaijan' },
  { code: 'OM', name: 'Oman' },
  { code: 'MT', name: 'Malta' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'PF', name: 'French Polynesia' },
  { code: 'AL', name: 'Albania' },
  { code: 'LA', name: "Lao People's Democratic Republic" },
  { code: 'IR', name: 'Islamic Republic of Iran' },
  { code: 'GP', name: 'Guadeloupe' },
  { code: 'AM', name: 'Armenia' },
  { code: 'MU', name: 'Mauritius' },
  { code: 'MP', name: 'Northern Mariana Islands' },
  { code: 'PS', name: 'State of Palestine' },
  { code: 'MQ', name: 'Martinique' },
  { code: 'NC', name: 'New Caledonia' },
  { code: 'SY', name: 'Syrian Arab Republic' },
  { code: 'ME', name: 'Montenegro' },
  { code: 'BZ', name: 'Belize' },
  { code: 'MG', name: 'Madagascar' },
  { code: 'BB', name: 'Barbados' },
  { code: 'SR', name: 'Suriname' },
  { code: 'BS', name: 'Bahamas' },
  { code: 'KE', name: 'Kenya' },
  { code: 'JE', name: 'Jersey' },
  { code: 'IM', name: 'Isle of Man' },
  { code: 'GF', name: 'French Guiana' },
  { code: 'FO', name: 'Faroe Islands' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'LY', name: 'Libya' },
  { code: 'GY', name: 'Guyana' },
  { code: 'AW', name: 'Aruba' },
  { code: 'SD', name: 'Sudan' },
  { code: 'GL', name: 'Greenland' },
  { code: 'GH', name: 'Ghana' },
  { code: 'BM', name: 'Bermuda' },
  { code: 'NA', name: 'Namibia' },
  { code: 'GG', name: 'Guernsey' },
  { code: 'AX', name: 'Aland Islands' },
  { code: 'CI', name: "Cote D'Ivoire" },
  { code: 'CW', name: 'Curaçao' },
  { code: 'VI', name: 'Virgin Islands, U.S.' },
  { code: 'GI', name: 'Gibraltar' },
  { code: 'LC', name: 'Saint Lucia' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'BW', name: 'Botswana' },
  { code: 'FJ', name: 'Fiji' },
  { code: 'AD', name: 'Andorra' },
  { code: 'CV', name: 'Cabo Verde' },
  { code: 'YT', name: 'Mayotte' },
  { code: 'KY', name: 'Cayman Islands' },
  { code: 'AO', name: 'Angola' },
  { code: 'DM', name: 'Dominica' },
  { code: 'AG', name: 'Antigua and Barbuda' },
  { code: 'MF', name: 'Saint Martin' },
  { code: 'ET', name: 'Ethiopia' },
  { code: 'CU', name: 'Cuba' },
  { code: 'XK', name: 'Kosovo' },
  { code: 'GA', name: 'Gabon' },
  { code: 'SM', name: 'San Marino' },
  { code: 'MZ', name: 'Mozambique' },
  { code: 'SN', name: 'Senegal' },
  { code: 'MC', name: 'Monaco' },
  { code: 'ZM', name: 'Zambia' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines' },
  { code: 'ZW', name: 'Zimbabwe' },
  { code: 'TJ', name: 'Tajikistan' },
  { code: 'TZ', name: 'United Republic of Tanzania' },
  { code: 'UG', name: 'Uganda' },
  { code: 'PM', name: 'Saint Pierre and Miquelon' },
  { code: 'TM', name: 'Turkmenistan' },
  { code: 'KN', name: 'Saint Kitts and Nevis' },
  { code: 'BT', name: 'Bhutan' },
  { code: 'HT', name: 'Haiti' },
  { code: 'GD', name: 'Grenada' },
  { code: 'YE', name: 'Yemen' },
  { code: 'TG', name: 'Togo' },
  { code: 'AP', name: 'Asia/Pacific Region' },
  { code: 'FM', name: 'Federated States of Micronesia' },
  { code: 'RW', name: 'Rwanda' },
  { code: 'AI', name: 'Anguilla' },
  { code: 'VU', name: 'Vanuatu' },
  { code: 'DJ', name: 'Djibouti' },
  { code: 'CM', name: 'Cameroon' },
  { code: 'MH', name: 'Marshall Islands' },
  { code: 'TL', name: 'Timor-Leste' },
  { code: 'TC', name: 'Turks and Caicos Islands' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen' },
  { code: 'EU', name: 'Europe' },
  { code: 'AS', name: 'American Samoa' },
  { code: 'MW', name: 'Malawi' },
  { code: 'SZ', name: 'Eswatini' },
  { code: 'SC', name: 'Seychelles' },
  { code: 'CK', name: 'Cook Islands' },
  { code: 'NE', name: 'Niger' },
  { code: 'BL', name: 'Saint Barthelemy' },
  { code: 'WS', name: 'Samoa' },
  { code: 'CD', name: 'The Democratic Republic of the Congo' },
  { code: 'PG', name: 'Papua New Guinea' },
  { code: 'BJ', name: 'Benin' },
  { code: 'MR', name: 'Mauritania' },
  { code: 'CG', name: 'Congo' },
  { code: 'ML', name: 'Mali' },
  { code: 'SX', name: 'Sint Maarten' },
  { code: 'BQ', name: 'Caribbean Netherlands' },
  { code: 'VG', name: 'Virgin Islands, British' },
  { code: 'PW', name: 'Palau' },
  { code: 'BF', name: 'Burkina Faso' },
  { code: 'AF', name: 'Afghanistan' },
  { code: 'GN', name: 'Guinea' },
  { code: 'TK', name: 'Tokelau' },
  { code: 'GM', name: 'Gambia' },
  { code: 'SO', name: 'Somalia' },
  { code: 'LS', name: 'Lesotho' },
  { code: 'ST', name: 'Sao Tome and Principe' },
  { code: 'SL', name: 'Sierra Leone' },
  { code: 'CX', name: 'Christmas Island' },
  { code: 'TD', name: 'Chad' },
  { code: 'BI', name: 'Burundi' },
  { code: 'NF', name: 'Norfolk Island' },
  { code: 'FK', name: 'Falkland Islands (Malvinas)' },
  { code: 'ER', name: 'Eritrea' },
  { code: 'KM', name: 'Comoros' },
  { code: 'GQ', name: 'Equatorial Guinea' },
  { code: 'LR', name: 'Liberia' },
  { code: 'TO', name: 'Tonga' },
  { code: 'WF', name: 'Wallis and Futuna' },
  { code: 'GW', name: 'Guinea-Bissau' },
  { code: 'TV', name: 'Tuvalu' },
  { code: 'SB', name: 'Solomon Islands' },
  { code: 'CC', name: 'Cocos (Keeling) Islands' },
  { code: 'BV', name: 'Bouvet Island' },
  { code: 'AN', name: 'Netherlands Antilles' },
  { code: 'KI', name: 'Kiribati' },
  { code: 'MS', name: 'Montserrat' },
  { code: 'NR', name: 'Nauru' },
  { code: 'NU', name: 'Niue' },
  { code: 'PN', name: 'Pitcairn' },
  { code: 'CF', name: 'Central African Republic' },
]

const countriesToCheck = computed(() => store.state.countries);

const searchQuery = ref("");
const searchQueryResults = computed(() => {
  return jsonCountries.filter(country => {
    return country.name.toLowerCase().includes(searchQuery.value.toLowerCase())
  })
})

const addCountry = (countryCode: string) => {
  store.dispatch("addCountry", countryCode);
};
const removeCountry = (countryCode: string) => {
  store.dispatch("removeCountry", countryCode);
}
</script>

<template>
  <div class="setting">
    <p class="font-semibold">Countries</p>
    <div class="flex gap-2 h-full max-h-64">
      <div class="flex flex-col flex-1 gap-2">
        <p>Countries to Add</p>
        <input v-model="searchQuery" type="text" placeholder="Search" class="form-element max-w-full">
        <transition-group name="array" tag="div" class="listbox">
          <p v-for="country in searchQueryResults" :key="country.code" class="hover:bg-gray-700 p-1"
            @dblclick="addCountry(country.code)">
            {{ country.code }} - {{ country.name }}
          </p>
        </transition-group>
      </div>

      <div class="flex flex-col flex-1">
        <p>Countries to Check</p>
        <transition-group name="array" tag="div" class="listbox">
          <p v-for="countryCode in countriesToCheck" :key="countryCode" class="hover:bg-gray-700 p-1"
            @dblclick="removeCountry(countryCode)">
            {{ countryCode }}
          </p>
        </transition-group>
      </div>
    </div>
  </div>
</template>
